# Generated by Django 4.1.3 on 2022-12-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('sal_cd', models.AutoField(db_column='SAL_CD', primary_key=True, serialize=False)),
                ('sal_mthd', models.CharField(db_column='SAL_MTHD', max_length=3)),
                ('sal_nm', models.CharField(db_column='SAL_NM', max_length=200)),
                ('sal_mng_nm', models.CharField(blank=True, db_column='SAL_MNG_NM', max_length=200, null=True)),
                ('sal_snm', models.CharField(blank=True, db_column='SAL_SNM', max_length=50, null=True)),
                ('cost_price', models.IntegerField(blank=True, db_column='COST_PRICE', null=True)),
                ('sal_amt', models.PositiveIntegerField(db_column='SAL_AMT')),
                ('dlv_typ', models.CharField(db_column='DLV_TYP', max_length=3)),
                ('cash_use_yn', models.CharField(db_column='CASH_USE_YN', max_length=1)),
                ('point_use_yn', models.CharField(db_column='POINT_USE_YN', max_length=1)),
                ('cpn_use_yn', models.CharField(db_column='CPN_USE_YN', max_length=1)),
                ('sal_sdt', models.DateField(blank=True, db_column='SAL_SDT', null=True)),
                ('sal_edt', models.DateField(blank=True, db_column='SAL_EDT', null=True)),
                ('state', models.CharField(db_column='STATE', max_length=2)),
                ('reg_dttm', models.DateTimeField(db_column='REG_DTTM')),
                ('adm_id', models.CharField(db_column='ADM_ID', max_length=20)),
                ('basic_yn', models.CharField(blank=True, db_column='BASIC_YN', max_length=1, null=True)),
                ('dp_state', models.CharField(db_column='DP_STATE', max_length=3)),
                ('use_mthds', models.CharField(blank=True, db_column='USE_MTHDS', max_length=10, null=True)),
                ('sal_thum', models.CharField(blank=True, db_column='SAL_THUM', max_length=100, null=True)),
                ('sal_thum2', models.CharField(blank=True, db_column='SAL_THUM2', max_length=100, null=True)),
                ('sal_intro', models.TextField(blank=True, db_column='SAL_INTRO', null=True)),
                ('sal_sintro', models.CharField(blank=True, db_column='SAL_SINTRO', max_length=200, null=True)),
                ('sal_bft', models.CharField(blank=True, db_column='SAL_BFT', max_length=100, null=True)),
                ('sal_cate', models.IntegerField(db_column='SAL_CATE')),
                ('sal_scate', models.IntegerField(db_column='SAL_SCATE')),
                ('etc_gb', models.CharField(db_column='ETC_GB', max_length=3)),
                ('dp_sal_cd', models.IntegerField(blank=True, db_column='DP_SAL_CD', null=True)),
                ('grp_seq', models.IntegerField(blank=True, db_column='GRP_SEQ', null=True)),
                ('dp_info', models.CharField(blank=True, db_column='DP_INFO', max_length=20, null=True)),
                ('dp_ord', models.PositiveSmallIntegerField(blank=True, db_column='DP_ORD', null=True)),
                ('menu_nm', models.CharField(blank=True, db_column='MENU_NM', max_length=100, null=True)),
                ('r_badge', models.CharField(blank=True, db_column='R_BADGE', max_length=50, null=True)),
                ('dp_state_yn', models.CharField(db_column='DP_STATE_YN', max_length=1)),
                ('action_yn', models.CharField(blank=True, db_column='ACTION_YN', max_length=2, null=True)),
                ('top_yn', models.CharField(blank=True, db_column='TOP_YN', max_length=1, null=True)),
                ('dvs_cnt', models.IntegerField(blank=True, db_column='DVS_CNT', null=True)),
                ('etc_gb2', models.DateField(blank=True, db_column='ETC_GB2', null=True)),
                ('sal_dt', models.TextField(blank=True, db_column='SAL_DT', null=True)),
                ('store', models.IntegerField(blank=True, db_column='STORE', null=True)),
                ('sal_url', models.CharField(blank=True, db_column='SAL_URL', max_length=100, null=True)),
                ('chr_stage', models.IntegerField(blank=True, db_column='CHR_STAGE', null=True)),
                ('live_type', models.IntegerField(blank=True, db_column='LIVE_TYPE', null=True)),
                ('live_limit', models.IntegerField(blank=True, db_column='LIVE_LIMIT', null=True)),
                ('live_manual', models.IntegerField(blank=True, db_column='LIVE_MANUAL', null=True)),
                ('live_sal_sdt', models.DateTimeField(blank=True, db_column='LIVE_SAL_SDT', null=True)),
                ('live_sal_edt', models.DateTimeField(blank=True, db_column='LIVE_SAL_EDT', null=True)),
                ('cpn_mas', models.IntegerField(blank=True, db_column='CPN_MAS', null=True)),
                ('off_grp', models.IntegerField(blank=True, db_column='OFF_GRP', null=True)),
            ],
            options={
                'db_table': 'GOODS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GoodsDtl',
            fields=[
                ('dtl_seq', models.AutoField(db_column='DTL_SEQ', primary_key=True, serialize=False)),
                ('sal_cd', models.IntegerField(db_column='SAL_CD')),
                ('info_knd', models.CharField(db_collation='utf8_general_ci', db_column='INFO_KND', max_length=3)),
                ('info_img', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='INFO_IMG', max_length=200, null=True)),
                ('info_ttl', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='INFO_TTL', max_length=200, null=True)),
                ('info_cmnt', models.TextField(blank=True, db_column='INFO_CMNT', null=True)),
                ('ref_vod', models.IntegerField(blank=True, db_column='REF_VOD', null=True)),
                ('ref_ttl', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='REF_TTL', max_length=200, null=True)),
                ('ref_cmnt', models.TextField(blank=True, db_column='REF_CMNT', null=True)),
                ('use_yn', models.CharField(db_collation='utf8_general_ci', db_column='USE_YN', max_length=1)),
                ('dp_ord', models.IntegerField(db_column='DP_ORD')),
                ('reg_dttm', models.DateTimeField(db_column='REG_DTTM')),
                ('mdf_dttm', models.DateTimeField(blank=True, db_column='MDF_DTTM', null=True)),
            ],
            options={
                'db_table': 'GOODS_DTL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProdKnd',
            fields=[
                ('prod_knd_cd', models.CharField(db_column='PROD_KND_CD', max_length=2, primary_key=True, serialize=False)),
                ('prod_knd_nm', models.CharField(blank=True, db_column='PROD_KND_NM', max_length=20, null=True)),
                ('reg_dttm', models.DateTimeField(db_column='REG_DTTM')),
                ('adm_id', models.CharField(blank=True, db_column='ADM_ID', max_length=20, null=True)),
                ('note', models.CharField(blank=True, db_column='NOTE', max_length=100, null=True)),
                ('use_yn', models.CharField(db_column='USE_YN', max_length=1)),
                ('dlv_yn', models.CharField(db_column='DLV_YN', max_length=1)),
                ('del_yn', models.CharField(blank=True, db_column='DEL_YN', max_length=1, null=True)),
            ],
            options={
                'db_table': 'PROD_KND',
                'managed': False,
            },
        ),
    ]
