from django.db import models

# Create your models here.
class SiteEvt(models.Model):
    no = models.AutoField(primary_key=True)
    adm_key = models.CharField(max_length=20)
    adm_id = models.CharField(max_length=20)
    adm_nm = models.CharField(max_length=20)
    evt_sdt = models.DateTimeField()
    evt_edt = models.DateTimeField()
    dp_sdt = models.DateTimeField(blank=True, null=True)
    dp_edt = models.DateTimeField(blank=True, null=True)
    kisu_yn = models.CharField(max_length=1, blank=True, null=True)
    title = models.CharField(max_length=50)
    content = models.TextField()
    wdate = models.DateTimeField()
    hit = models.IntegerField()
    dn_cnt = models.IntegerField()
    scrap_cnt = models.IntegerField()
    display = models.CharField(max_length=1)
    filename = models.CharField(max_length=100)
    upload_file = models.CharField(max_length=50)
    winlist = models.TextField()
    board_del = models.CharField(max_length=1)
    edate = models.DateTimeField(blank=True, null=True)
    pv = models.IntegerField()
    evt_path = models.CharField(max_length=30, blank=True, null=True)
    evt_btn = models.CharField(max_length=1, blank=True, null=True)
    meta_ttl = models.CharField(max_length=100, blank=True, null=True)
    meta_dsc = models.CharField(max_length=300, blank=True, null=True)
    meta_key = models.CharField(max_length=300, blank=True, null=True)
    og_ttl = models.CharField(max_length=100, blank=True, null=True)
    og_dsc = models.CharField(max_length=300, blank=True, null=True)
    og_img = models.CharField(max_length=100, blank=True, null=True)
    og_url = models.CharField(max_length=100, blank=True, null=True)
    twt_ttl = models.CharField(max_length=100, blank=True, null=True)
    twt_dsc = models.CharField(max_length=300, blank=True, null=True)
    twt_img = models.CharField(max_length=100, blank=True, null=True)
    twt_url = models.CharField(max_length=100, blank=True, null=True)
    rvw_yn = models.CharField(max_length=1)
    etc_yn = models.CharField(max_length=1, blank=True, null=True)
    json_data = models.TextField(blank=True, null=True)
    json_schema = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'site_evt'

class UserBoard(models.Model):
    no = models.AutoField(primary_key=True)
    board_no = models.IntegerField()
    rank = models.IntegerField()
    title = models.CharField(max_length=100, db_collation='utf8_general_ci')
    content = models.TextField()
    usr_key = models.CharField(max_length=20, db_collation='utf8_general_ci')
    id = models.CharField(max_length=100, db_collation='utf8_general_ci', blank=True, null=True)
    name = models.CharField(max_length=20, db_collation='utf8_general_ci')
    job = models.CharField(max_length=20, db_collation='utf8_general_ci')
    chr_cd = models.IntegerField()
    tch_cd = models.IntegerField(blank=True, null=True)
    wdate = models.DateTimeField()
    dp_date = models.DateTimeField()
    dp_sdttm = models.DateTimeField(blank=True, null=True)
    dp_edttm = models.DateTimeField(blank=True, null=True)
    hit = models.IntegerField()
    dn_cnt = models.IntegerField()
    scrap_cnt = models.IntegerField()
    ip = models.CharField(max_length=15, db_collation='utf8_general_ci')
    filename = models.CharField(max_length=100, db_collation='utf8_general_ci')
    upload_file = models.CharField(max_length=100, db_collation='utf8_general_ci')
    thumb_url = models.CharField(max_length=100, db_collation='utf8_general_ci')
    comments = models.IntegerField()
    board_del = models.CharField(max_length=1, db_collation='utf8_general_ci')
    c_code = models.CharField(max_length=50, db_collation='utf8_general_ci')
    top = models.IntegerField()
    depth = models.CharField(max_length=20, db_collation='utf8_general_ci')
    re_yn = models.CharField(max_length=1, db_collation='utf8_general_ci', blank=True, null=True)
    category = models.CharField(max_length=50, db_collation='utf8_general_ci')
    display = models.IntegerField()
    board_type = models.CharField(max_length=1, db_collation='utf8_general_ci')
    and1 = models.TextField(db_collation='utf8_general_ci')
    and2 = models.TextField(db_collation='utf8_general_ci')
    and3 = models.TextField(db_collation='utf8_general_ci', blank=True, null=True)
    and4 = models.TextField(db_collation='utf8_general_ci', blank=True, null=True)
    and5 = models.TextField(db_collation='utf8_general_ci', blank=True, null=True)
    and6 = models.TextField(db_collation='utf8_general_ci', blank=True, null=True)
    and7 = models.TextField(db_collation='utf8_general_ci', blank=True, null=True)
    and8 = models.TextField(db_collation='utf8_general_ci', blank=True, null=True)
    and9 = models.TextField(db_collation='utf8_general_ci', blank=True, null=True)
    and10 = models.TextField(db_collation='utf8_general_ci', blank=True, null=True)
    and11 = models.TextField(db_collation='utf8_general_ci', blank=True, null=True)
    and12 = models.TextField(db_collation='utf8_general_ci', blank=True, null=True)
    edate = models.DateTimeField(blank=True, null=True)
    editer_yn = models.CharField(max_length=1, db_collation='utf8_general_ci')
    fake_comment = models.IntegerField(blank=True, null=True)
    target_typ = models.SmallIntegerField()

    class Meta:
        managed = False
        db_table = 'user_board'