# Generated by Django 4.1.3 on 2022-11-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsrInfo',
            fields=[
                ('usr_key', models.CharField(db_column='USR_KEY', max_length=20, primary_key=True, serialize=False)),
                ('pwd', models.CharField(blank=True, db_column='PWD', max_length=100, null=True)),
                ('usr_id', models.CharField(blank=True, db_column='USR_ID', max_length=100, null=True)),
                ('state', models.CharField(blank=True, db_column='STATE', max_length=2, null=True)),
                ('usr_typ', models.CharField(blank=True, db_column='USR_TYP', max_length=3, null=True)),
                ('usr_knd', models.CharField(blank=True, db_column='USR_KND', max_length=3, null=True)),
                ('usr_nm', models.CharField(blank=True, db_column='USR_NM', max_length=20, null=True)),
                ('gen', models.CharField(blank=True, db_column='GEN', max_length=1, null=True)),
                ('birth', models.CharField(blank=True, db_column='BIRTH', max_length=10, null=True)),
                ('lunisolar', models.CharField(blank=True, db_column='LUNISOLAR', max_length=1, null=True)),
                ('tel', models.CharField(blank=True, db_column='TEL', max_length=13, null=True)),
                ('htel', models.CharField(blank=True, db_column='HTEL', max_length=13, null=True)),
                ('email', models.CharField(blank=True, db_column='EMAIL', max_length=100, null=True)),
                ('zip', models.CharField(blank=True, db_column='ZIP', max_length=7, null=True)),
                ('addr1', models.CharField(blank=True, db_column='ADDR1', max_length=100, null=True)),
                ('addr2', models.CharField(blank=True, db_column='ADDR2', max_length=100, null=True)),
                ('reg_dttm', models.DateTimeField(blank=True, db_column='REG_DTTM', null=True)),
                ('join_dttm', models.DateTimeField(blank=True, db_column='JOIN_DTTM', null=True)),
                ('mdf_dttm', models.DateTimeField(blank=True, db_column='MDF_DTTM', null=True)),
                ('del_dttm', models.DateTimeField(blank=True, db_column='DEL_DTTM', null=True)),
                ('cash', models.IntegerField(blank=True, db_column='CASH', null=True)),
                ('point', models.IntegerField(blank=True, db_column='POINT', null=True)),
                ('not_pwd', models.IntegerField(blank=True, db_column='NOT_PWD', null=True)),
                ('last_login', models.DateTimeField(blank=True, db_column='LAST_LOGIN', null=True)),
                ('mthd', models.CharField(blank=True, db_column='MTHD', max_length=3, null=True)),
                ('sns_knd', models.CharField(blank=True, db_column='SNS_KND', max_length=3, null=True)),
                ('dvs_cnt', models.IntegerField(blank=True, db_column='DVS_CNT', null=True)),
                ('usr_thum', models.CharField(blank=True, db_column='USR_THUM', max_length=100, null=True)),
                ('sms_yn', models.CharField(blank=True, db_column='SMS_YN', max_length=1, null=True)),
                ('mail_yn', models.CharField(blank=True, db_column='MAIL_YN', max_length=1, null=True)),
                ('usr_eng_nm', models.CharField(blank=True, db_column='USR_ENG_NM', max_length=30, null=True)),
                ('job', models.CharField(blank=True, db_column='JOB', max_length=10, null=True)),
                ('usr_msg', models.CharField(blank=True, db_column='USR_MSG', max_length=255, null=True)),
                ('usr_img', models.CharField(blank=True, db_column='USR_IMG', max_length=100, null=True)),
            ],
            options={
                'db_table': 'USR_INFO',
                'managed': False,
            },
        ),
    ]
