# Generated by Django 4.1.3 on 2022-11-30 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsrDtl',
            fields=[
                ('usr_key', models.OneToOneField(db_column='USR_KEY', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rcm_id', models.CharField(blank=True, db_column='RCM_ID', max_length=20, null=True)),
                ('rcm_key', models.CharField(blank=True, db_column='RCM_KEY', max_length=20, null=True)),
                ('path', models.CharField(blank=True, db_column='PATH', max_length=3, null=True)),
                ('path_etc', models.CharField(blank=True, db_column='PATH_ETC', max_length=100, null=True)),
                ('job', models.CharField(blank=True, db_column='JOB', max_length=100, null=True)),
                ('job_career_years', models.IntegerField(blank=True, db_column='JOB_CAREER_YEARS', null=True)),
                ('goal', models.CharField(blank=True, db_column='GOAL', max_length=100, null=True)),
                ('pps', models.CharField(blank=True, db_column='PPS', max_length=100, null=True)),
                ('std_dt', models.CharField(blank=True, db_column='STD_DT', max_length=100, null=True)),
                ('std_lvl', models.CharField(blank=True, db_column='STD_LVL', max_length=3, null=True)),
                ('std_line', models.CharField(blank=True, db_column='STD_LINE', max_length=3, null=True)),
                ('sch_yaer', models.CharField(blank=True, db_column='SCH_YAER', max_length=3, null=True)),
                ('sms_yn', models.CharField(blank=True, db_column='SMS_YN', max_length=1, null=True)),
                ('mail_yn', models.CharField(blank=True, db_column='MAIL_YN', max_length=1, null=True)),
                ('dm_yn', models.CharField(blank=True, db_column='DM_YN', max_length=1, null=True)),
                ('usr_auth_seq', models.IntegerField(blank=True, db_column='USR_AUTH_SEQ', null=True)),
                ('band_cd', models.CharField(blank=True, db_column='BAND_CD', max_length=3, null=True)),
                ('ad_seq', models.CharField(blank=True, db_column='AD_SEQ', max_length=12, null=True)),
                ('etc1', models.CharField(blank=True, db_column='ETC1', max_length=100, null=True)),
                ('etc2', models.CharField(blank=True, db_column='ETC2', max_length=100, null=True)),
                ('step1_alim', models.CharField(blank=True, db_column='STEP1_ALIM', max_length=1, null=True)),
                ('step2_alim', models.CharField(blank=True, db_column='STEP2_ALIM', max_length=1, null=True)),
            ],
            options={
                'db_table': 'USR_DTL',
                'managed': False,
            },
        ),
    ]
