# Generated by Django 4.1.3 on 2022-11-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteEvt',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('adm_key', models.CharField(max_length=20)),
                ('adm_id', models.CharField(max_length=20)),
                ('adm_nm', models.CharField(max_length=20)),
                ('evt_sdt', models.DateTimeField()),
                ('evt_edt', models.DateTimeField()),
                ('dp_sdt', models.DateTimeField(blank=True, null=True)),
                ('dp_edt', models.DateTimeField(blank=True, null=True)),
                ('kisu_yn', models.CharField(blank=True, max_length=1, null=True)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('wdate', models.DateTimeField()),
                ('hit', models.IntegerField()),
                ('dn_cnt', models.IntegerField()),
                ('scrap_cnt', models.IntegerField()),
                ('display', models.CharField(max_length=1)),
                ('filename', models.CharField(max_length=100)),
                ('upload_file', models.CharField(max_length=50)),
                ('winlist', models.TextField()),
                ('board_del', models.CharField(max_length=1)),
                ('edate', models.DateTimeField(blank=True, null=True)),
                ('pv', models.IntegerField()),
                ('evt_path', models.CharField(blank=True, max_length=30, null=True)),
                ('evt_btn', models.CharField(blank=True, max_length=1, null=True)),
                ('meta_ttl', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_dsc', models.CharField(blank=True, max_length=300, null=True)),
                ('meta_key', models.CharField(blank=True, max_length=300, null=True)),
                ('og_ttl', models.CharField(blank=True, max_length=100, null=True)),
                ('og_dsc', models.CharField(blank=True, max_length=300, null=True)),
                ('og_img', models.CharField(blank=True, max_length=100, null=True)),
                ('og_url', models.CharField(blank=True, max_length=100, null=True)),
                ('twt_ttl', models.CharField(blank=True, max_length=100, null=True)),
                ('twt_dsc', models.CharField(blank=True, max_length=300, null=True)),
                ('twt_img', models.CharField(blank=True, max_length=100, null=True)),
                ('twt_url', models.CharField(blank=True, max_length=100, null=True)),
                ('rvw_yn', models.CharField(max_length=1)),
                ('etc_yn', models.CharField(blank=True, max_length=1, null=True)),
                ('json_data', models.TextField(blank=True, null=True)),
                ('json_schema', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'site_evt',
                'managed': False,
            },
        ),
    ]
