# Generated by Django 4.1.3 on 2022-11-23 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBoard',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('board_no', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('title', models.CharField(db_collation='utf8_general_ci', max_length=100)),
                ('content', models.TextField()),
                ('usr_key', models.CharField(db_collation='utf8_general_ci', max_length=20)),
                ('id', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=100, null=True)),
                ('name', models.CharField(db_collation='utf8_general_ci', max_length=20)),
                ('job', models.CharField(db_collation='utf8_general_ci', max_length=20)),
                ('chr_cd', models.IntegerField()),
                ('tch_cd', models.IntegerField(blank=True, null=True)),
                ('wdate', models.DateTimeField()),
                ('dp_date', models.DateTimeField()),
                ('dp_sdttm', models.DateTimeField(blank=True, null=True)),
                ('dp_edttm', models.DateTimeField(blank=True, null=True)),
                ('hit', models.IntegerField()),
                ('dn_cnt', models.IntegerField()),
                ('scrap_cnt', models.IntegerField()),
                ('ip', models.CharField(db_collation='utf8_general_ci', max_length=15)),
                ('filename', models.CharField(db_collation='utf8_general_ci', max_length=100)),
                ('upload_file', models.CharField(db_collation='utf8_general_ci', max_length=100)),
                ('thumb_url', models.CharField(db_collation='utf8_general_ci', max_length=100)),
                ('comments', models.IntegerField()),
                ('board_del', models.CharField(db_collation='utf8_general_ci', max_length=1)),
                ('c_code', models.CharField(db_collation='utf8_general_ci', max_length=50)),
                ('top', models.IntegerField()),
                ('depth', models.CharField(db_collation='utf8_general_ci', max_length=20)),
                ('re_yn', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=1, null=True)),
                ('category', models.CharField(db_collation='utf8_general_ci', max_length=50)),
                ('display', models.IntegerField()),
                ('board_type', models.CharField(db_collation='utf8_general_ci', max_length=1)),
                ('and1', models.TextField(db_collation='utf8_general_ci')),
                ('and2', models.TextField(db_collation='utf8_general_ci')),
                ('and3', models.TextField(blank=True, db_collation='utf8_general_ci', null=True)),
                ('and4', models.TextField(blank=True, db_collation='utf8_general_ci', null=True)),
                ('and5', models.TextField(blank=True, db_collation='utf8_general_ci', null=True)),
                ('and6', models.TextField(blank=True, db_collation='utf8_general_ci', null=True)),
                ('and7', models.TextField(blank=True, db_collation='utf8_general_ci', null=True)),
                ('and8', models.TextField(blank=True, db_collation='utf8_general_ci', null=True)),
                ('and9', models.TextField(blank=True, db_collation='utf8_general_ci', null=True)),
                ('and10', models.TextField(blank=True, db_collation='utf8_general_ci', null=True)),
                ('and11', models.TextField(blank=True, db_collation='utf8_general_ci', null=True)),
                ('and12', models.TextField(blank=True, db_collation='utf8_general_ci', null=True)),
                ('edate', models.DateTimeField(blank=True, null=True)),
                ('editer_yn', models.CharField(db_collation='utf8_general_ci', max_length=1)),
                ('fake_comment', models.IntegerField(blank=True, null=True)),
                ('target_typ', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'user_board',
                'managed': False,
            },
        ),
    ]
